on: push
name: build and test app
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.5'
    - run: flutter pub get
    # - run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle

    # steps:
    # - uses: actions/checkout@v1

    # - name: install dependencies
    #   uses: steebchen/flutter@v1.1.0
    #   with:
    #     flutter-version: '2.14.0'
    #     args: pub get

    # - name: run tests
    #   uses: steebchen/flutter@v1.1.0
    #   with:
    #     args: test

    # - name: build apk
    #   uses: steebchen/flutter@v1.1.0
    #   with:
    #     args: build apk --release
