on: push
name: build and test app
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.5'
    - run: flutter pub get
    # - run: flutter test
    - run: flutter build apk --release
    - run: flutter build appbundle  
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: HarithaSeddik/CI_Testing
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Testers
        file: build/app/outputs/flutter-apk/app-release.apk
        notifyTesters: true
        debug: false
      
      